project_id = "gthtvpujwukbfgokghne"

[api]
schemas = ["public", "base_custos", "graphql_public"]
extra_search_path = ["public", "extensions", "base_custos"]

[functions.fluxo-0-listar-emissoes]
verify_jwt = false

[functions.fluxo-0-detalhes-emissao]
verify_jwt = false

[functions.fluxo-1-criar-emissao]
verify_jwt = false

[functions.fluxo-1-atualizar-emissao]
verify_jwt = false

[functions.fluxo-1-salvar-custos]
verify_jwt = false

[functions.fluxo-2-gerar-pdf]
verify_jwt = false

[functions.fluxo-2-finalizar-proposta]
verify_jwt = false

[functions.fluxo_custos_por_combinacao]
verify_jwt = false

[functions.custodiab3_cr]
verify_jwt = false

[functions.custodiab3_cra]
verify_jwt = false

[functions.custodiab3_deb]
verify_jwt = false

[functions.anbima_cri]
verify_jwt = false

[functions.taxacvm]
verify_jwt = false

[functions.anbima_todos]
verify_jwt = false

[functions.registrob3_cr]
verify_jwt = false

[functions.registrob3_debpub]
verify_jwt = false

[functions.registrob3_debpriv]
verify_jwt = false

[functions.buscar-cnpj]
verify_jwt = false
